"""added dead letter queue

Revision ID: 36e1ecad3057
Revises: 6f6173221096
Create Date: 2026-06-30 15:12:46.703648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e1ecad3057'
down_revision: Union[str, Sequence[str], None] = '6f6173221096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('error_reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letters_chat_id'), 'dead_letters', ['chat_id'], unique=False)
    op.create_index(op.f('ix_dead_letters_id'), 'dead_letters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dead_letters_id'), table_name='dead_letters')
    op.drop_index(op.f('ix_dead_letters_chat_id'), table_name='dead_letters')
    op.drop_table('dead_letters')
    # ### end Alembic commands ###
